parser grammar TestExecutorParser ;

import TestExecutorParser, TestResourceParser, PdslCommonParser, TestRunResultCommonParser ;
options {tokenVocab=TestExecutorLexer ; }

givenTheTestExecutorIsSpecified : GIVEN_THE_TEST_EXECUTOR_IS textInDoubleQuotesEnd ;
givenTheGrammarListener : GIVEN_THE_GRAMMAR_PARSE_TREE_LISTENER textInDoubleQuotesEnd;
givenTheSubgrammarListener : GIVEN_THE_SUBGRAMMAR_PARSE_TREE_LISTENER textInDoubleQuotesEnd ;
whenTheGherkinTestExecutorRunsWithTagExpression : WHEN_THE_GHERKIN_TEST_EXECUTOR_RUNS_WITH_TAG_EXPRESSION textInDoubleQuotesEnd ;
givenTheGrammarPhraseFilter : GIVEN_GRAMMAR_PHRASE_FILTER_IS textInDoubleQuotesEnd ;
givenTheSubgrammarPhraseFilter : GIVEN_SUBGRAMMAR_PHRASE_FILTER_IS textInDoubleQuotesEnd ;