lexer grammar RestaurantRecognizerLexer;

import RestaurantCustomerServiceLexer, RestaurantCustomerLexer,
 RestaurantDishwasherLexer, RestaurantKitchenLexer, RestaurantReservationLexer,
 RestaurantPorterLexer, RestaurantWaiterLexer, RestaurantStationChefLexer;