:toc:
ifndef::env-github[]
include::quickstart_beginning_section.adoc[]
endif::[]

ifdef::env-github[]
NOTE::Since you are viewing this document on GitHub please complete
the steps at the below link before proceeding:

https://github.com/google/polymorphicDSL/blob/main/documentation/tutorials/quickstart_beginning_section.adoc
endif::[]


== Implement the runner

The runner is where you execute the tests. You specify the interpreter to use and which files to read with it. Finally you specify the listener to use that will fire off methods every time a matching phrase is found.

----
package com.pdsl.quickstart;

import com.pdsl.runners.PdslGherkinApplication;
import com.pdsl.runners.PdslTest;
import com.pdsl.runners.junit.PdslGherkinJUnit4Runner;
import org.antlr.v4.runtime.tree.ParseTreeListener;
import org.junit.runner.RunWith;
import com.example.MyFirstLexer;
import com.example.MyFirstParser;

import javax.inject.Provider;

@RunWith(PdslGherkinJUnit4Runner.class)
@PdslGherkinApplication(
        resourceRoot = "src/test/resources/features"
)
public class PdslQuickstartTest {

    @PdslTest(
            parser = MyFirstParser.class,
            lexer = MyFirstLexer.class,
            listener = PdslQuickstartTest.MyFirstPdslProvider.class)
    public void myFirstPdslTest() {}

    // The provider builds the listener for the PDSL framework.
    // It must be static so that it can be seen by the underlying framework.
    // It also must have a default constructor (no parameters).
    // It can be convenient to make it a static class rather than put it in it's
    // own file so that the person running the test can understand if there are
    // special inputs or not (dependency injection, etc).
    public static class MyFirstPdslProvider implements Provider<ParseTreeListener> {

        @Override
        public ParseTreeListener get() {
            return new MyFirstPdslListener();
        }
    }
}
----

After this, simply run your tests using `mvn clean test`.

NOTE: If you noticed you made a mistake in your parser, make sure to run mvn antlr4:antlr4 to regenerate the parser, otherwise you might continue to get the same errors because you're using the old one! Some IDEs such as IntelliJ also have plugins you can download from their marketplace to create the "recognizer" by right-clicking the grammar files.


== Next Steps

PDSL was designed to solve problems for more complicated than we've seen in this tutorial. If you want to create your own language for testing instead of using Gherkin like we did here, see <<custom_grammar.adoc#, this guide>>. Otherwise proceed to <<gherkin_scalability_tutorial.adoc#, the gherkin scalability tutorial>>.

