// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/pdsl/reports/proto/StrategicReportData.proto

package com.pdsl.reports.proto;

public interface OperationalReportDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.pdsl.reports.proto.OperationalReportData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string application = 1;</code>
   */
  java.lang.String getApplication();
  /**
   * <code>string application = 1;</code>
   */
  com.google.protobuf.ByteString
      getApplicationBytes();

  /**
   * <code>repeated .com.pdsl.reports.proto.TacticalReportData tactical_report_data = 2;</code>
   */
  java.util.List<com.pdsl.reports.proto.TacticalReportData> 
      getTacticalReportDataList();
  /**
   * <code>repeated .com.pdsl.reports.proto.TacticalReportData tactical_report_data = 2;</code>
   */
  com.pdsl.reports.proto.TacticalReportData getTacticalReportData(int index);
  /**
   * <code>repeated .com.pdsl.reports.proto.TacticalReportData tactical_report_data = 2;</code>
   */
  int getTacticalReportDataCount();
  /**
   * <code>repeated .com.pdsl.reports.proto.TacticalReportData tactical_report_data = 2;</code>
   */
  java.util.List<? extends com.pdsl.reports.proto.TacticalReportDataOrBuilder> 
      getTacticalReportDataOrBuilderList();
  /**
   * <code>repeated .com.pdsl.reports.proto.TacticalReportData tactical_report_data = 2;</code>
   */
  com.pdsl.reports.proto.TacticalReportDataOrBuilder getTacticalReportDataOrBuilder(
      int index);
}
