// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/pdsl/reports/proto/StrategicReportData.proto

package com.pdsl.reports.proto;

public final class StrategicReportDataOuterClass {
  private StrategicReportDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pdsl_reports_proto_StrategicReportData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pdsl_reports_proto_StrategicReportData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pdsl_reports_proto_OperationalReportData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pdsl_reports_proto_OperationalReportData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pdsl_reports_proto_TacticalReportData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pdsl_reports_proto_TacticalReportData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pdsl_reports_proto_TacticalReportData_ContextToTestCasesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pdsl_reports_proto_TacticalReportData_ContextToTestCasesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pdsl_reports_proto_TestCaseGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pdsl_reports_proto_TestCaseGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pdsl_reports_proto_TechnicalReportData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pdsl_reports_proto_TechnicalReportData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n>src/main/java/com/pdsl/reports/proto/S" +
      "trategicReportData.proto\022\026com.pdsl.repor" +
      "ts.proto\"e\n\023StrategicReportData\022N\n\027opera" +
      "tional_report_data\030\001 \003(\0132-.com.pdsl.repo" +
      "rts.proto.OperationalReportData\"v\n\025Opera" +
      "tionalReportData\022\023\n\013application\030\001 \001(\t\022H\n" +
      "\024tactical_report_data\030\002 \003(\0132*.com.pdsl.r" +
      "eports.proto.TacticalReportData\"\371\001\n\022Tact" +
      "icalReportData\022\036\n\026unfiltered_phrase_body" +
      "\030\001 \003(\t\022a\n\025context_to_test_cases\030\002 \003(\0132B." +
      "com.pdsl.reports.proto.TacticalReportDat" +
      "a.ContextToTestCasesEntry\032`\n\027ContextToTe" +
      "stCasesEntry\022\013\n\003key\030\001 \001(\t\0224\n\005value\030\002 \001(\013" +
      "2%.com.pdsl.reports.proto.TestCaseGroup:" +
      "\0028\001\"[\n\rTestCaseGroup\022J\n\025technical_report" +
      "_data\030\001 \003(\0132+.com.pdsl.reports.proto.Tec" +
      "hnicalReportData\"\317\002\n\023TechnicalReportData" +
      "\022\027\n\017test_case_title\030\001 \001(\t\022B\n\006status\030\002 \001(" +
      "\01622.com.pdsl.reports.proto.TechnicalRepo" +
      "rtData.Status\022\026\n\016failing_phrase\030\003 \001(\t\022\026\n" +
      "\016failure_reason\030\004 \001(\t\022\034\n\024failing_phrase_" +
      "index\030\005 \001(\r\022\034\n\024filtered_phrase_body\030\006 \003(" +
      "\t\022&\n\036phrases_skipped_due_to_failure\030\007 \001(" +
      "\r\"G\n\006Status\022\026\n\022STATUS_UNSPECIFIED\020\000\022\n\n\006P" +
      "ASSED\020\001\022\n\n\006FAILED\020\002\022\r\n\tDUPLICATE\020\003B\002P\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_pdsl_reports_proto_StrategicReportData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_pdsl_reports_proto_StrategicReportData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pdsl_reports_proto_StrategicReportData_descriptor,
        new java.lang.String[] { "OperationalReportData", });
    internal_static_com_pdsl_reports_proto_OperationalReportData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_pdsl_reports_proto_OperationalReportData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pdsl_reports_proto_OperationalReportData_descriptor,
        new java.lang.String[] { "Application", "TacticalReportData", });
    internal_static_com_pdsl_reports_proto_TacticalReportData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_pdsl_reports_proto_TacticalReportData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pdsl_reports_proto_TacticalReportData_descriptor,
        new java.lang.String[] { "UnfilteredPhraseBody", "ContextToTestCases", });
    internal_static_com_pdsl_reports_proto_TacticalReportData_ContextToTestCasesEntry_descriptor =
      internal_static_com_pdsl_reports_proto_TacticalReportData_descriptor.getNestedTypes().get(0);
    internal_static_com_pdsl_reports_proto_TacticalReportData_ContextToTestCasesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pdsl_reports_proto_TacticalReportData_ContextToTestCasesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_pdsl_reports_proto_TestCaseGroup_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_pdsl_reports_proto_TestCaseGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pdsl_reports_proto_TestCaseGroup_descriptor,
        new java.lang.String[] { "TechnicalReportData", });
    internal_static_com_pdsl_reports_proto_TechnicalReportData_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_pdsl_reports_proto_TechnicalReportData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pdsl_reports_proto_TechnicalReportData_descriptor,
        new java.lang.String[] { "TestCaseTitle", "Status", "FailingPhrase", "FailureReason", "FailingPhraseIndex", "FilteredPhraseBody", "PhrasesSkippedDueToFailure", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
