// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/pdsl/reports/proto/StrategicReportData.proto

package com.pdsl.reports.proto;

public interface StrategicReportDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.pdsl.reports.proto.StrategicReportData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.pdsl.reports.proto.OperationalReportData operational_report_data = 1;</code>
   */
  java.util.List<com.pdsl.reports.proto.OperationalReportData> 
      getOperationalReportDataList();
  /**
   * <code>repeated .com.pdsl.reports.proto.OperationalReportData operational_report_data = 1;</code>
   */
  com.pdsl.reports.proto.OperationalReportData getOperationalReportData(int index);
  /**
   * <code>repeated .com.pdsl.reports.proto.OperationalReportData operational_report_data = 1;</code>
   */
  int getOperationalReportDataCount();
  /**
   * <code>repeated .com.pdsl.reports.proto.OperationalReportData operational_report_data = 1;</code>
   */
  java.util.List<? extends com.pdsl.reports.proto.OperationalReportDataOrBuilder> 
      getOperationalReportDataOrBuilderList();
  /**
   * <code>repeated .com.pdsl.reports.proto.OperationalReportData operational_report_data = 1;</code>
   */
  com.pdsl.reports.proto.OperationalReportDataOrBuilder getOperationalReportDataOrBuilder(
      int index);
}
