// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/pdsl/reports/proto/StrategicReportData.proto

package com.pdsl.reports.proto;

public interface TacticalReportDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.pdsl.reports.proto.TacticalReportData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string unfiltered_phrase_body = 1;</code>
   */
  java.util.List<java.lang.String>
      getUnfilteredPhraseBodyList();
  /**
   * <code>repeated string unfiltered_phrase_body = 1;</code>
   */
  int getUnfilteredPhraseBodyCount();
  /**
   * <code>repeated string unfiltered_phrase_body = 1;</code>
   */
  java.lang.String getUnfilteredPhraseBody(int index);
  /**
   * <code>repeated string unfiltered_phrase_body = 1;</code>
   */
  com.google.protobuf.ByteString
      getUnfilteredPhraseBodyBytes(int index);

  /**
   * <code>map&lt;string, .com.pdsl.reports.proto.TestCaseGroup&gt; context_to_test_cases = 2;</code>
   */
  int getContextToTestCasesCount();
  /**
   * <code>map&lt;string, .com.pdsl.reports.proto.TestCaseGroup&gt; context_to_test_cases = 2;</code>
   */
  boolean containsContextToTestCases(
      java.lang.String key);
  /**
   * Use {@link #getContextToTestCasesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.pdsl.reports.proto.TestCaseGroup>
  getContextToTestCases();
  /**
   * <code>map&lt;string, .com.pdsl.reports.proto.TestCaseGroup&gt; context_to_test_cases = 2;</code>
   */
  java.util.Map<java.lang.String, com.pdsl.reports.proto.TestCaseGroup>
  getContextToTestCasesMap();
  /**
   * <code>map&lt;string, .com.pdsl.reports.proto.TestCaseGroup&gt; context_to_test_cases = 2;</code>
   */

  com.pdsl.reports.proto.TestCaseGroup getContextToTestCasesOrDefault(
      java.lang.String key,
      com.pdsl.reports.proto.TestCaseGroup defaultValue);
  /**
   * <code>map&lt;string, .com.pdsl.reports.proto.TestCaseGroup&gt; context_to_test_cases = 2;</code>
   */

  com.pdsl.reports.proto.TestCaseGroup getContextToTestCasesOrThrow(
      java.lang.String key);
}
