// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/pdsl/reports/proto/StrategicReportData.proto

package com.pdsl.reports.proto;

/**
 * Protobuf type {@code com.pdsl.reports.proto.TechnicalReportData}
 */
public  final class TechnicalReportData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.pdsl.reports.proto.TechnicalReportData)
    TechnicalReportDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TechnicalReportData.newBuilder() to construct.
  private TechnicalReportData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TechnicalReportData() {
    testCaseTitle_ = "";
    status_ = 0;
    failingPhrase_ = "";
    failureReason_ = "";
    failingPhraseIndex_ = 0;
    filteredPhraseBody_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    phrasesSkippedDueToFailure_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TechnicalReportData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            testCaseTitle_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            failingPhrase_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            failureReason_ = s;
            break;
          }
          case 40: {

            failingPhraseIndex_ = input.readUInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              filteredPhraseBody_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000020;
            }
            filteredPhraseBody_.add(s);
            break;
          }
          case 56: {

            phrasesSkippedDueToFailure_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        filteredPhraseBody_ = filteredPhraseBody_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pdsl.reports.proto.StrategicReportDataOuterClass.internal_static_com_pdsl_reports_proto_TechnicalReportData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pdsl.reports.proto.StrategicReportDataOuterClass.internal_static_com_pdsl_reports_proto_TechnicalReportData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pdsl.reports.proto.TechnicalReportData.class, com.pdsl.reports.proto.TechnicalReportData.Builder.class);
  }

  /**
   * Protobuf enum {@code com.pdsl.reports.proto.TechnicalReportData.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATUS_UNSPECIFIED = 0;</code>
     */
    STATUS_UNSPECIFIED(0),
    /**
     * <code>PASSED = 1;</code>
     */
    PASSED(1),
    /**
     * <code>FAILED = 2;</code>
     */
    FAILED(2),
    /**
     * <code>DUPLICATE = 3;</code>
     */
    DUPLICATE(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STATUS_UNSPECIFIED = 0;</code>
     */
    public static final int STATUS_UNSPECIFIED_VALUE = 0;
    /**
     * <code>PASSED = 1;</code>
     */
    public static final int PASSED_VALUE = 1;
    /**
     * <code>FAILED = 2;</code>
     */
    public static final int FAILED_VALUE = 2;
    /**
     * <code>DUPLICATE = 3;</code>
     */
    public static final int DUPLICATE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 0: return STATUS_UNSPECIFIED;
        case 1: return PASSED;
        case 2: return FAILED;
        case 3: return DUPLICATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.pdsl.reports.proto.TechnicalReportData.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.pdsl.reports.proto.TechnicalReportData.Status)
  }

  private int bitField0_;
  public static final int TEST_CASE_TITLE_FIELD_NUMBER = 1;
  private volatile java.lang.Object testCaseTitle_;
  /**
   * <code>string test_case_title = 1;</code>
   */
  public java.lang.String getTestCaseTitle() {
    java.lang.Object ref = testCaseTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testCaseTitle_ = s;
      return s;
    }
  }
  /**
   * <code>string test_case_title = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTestCaseTitleBytes() {
    java.lang.Object ref = testCaseTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testCaseTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <code>.com.pdsl.reports.proto.TechnicalReportData.Status status = 2;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.com.pdsl.reports.proto.TechnicalReportData.Status status = 2;</code>
   */
  public com.pdsl.reports.proto.TechnicalReportData.Status getStatus() {
    @SuppressWarnings("deprecation")
    com.pdsl.reports.proto.TechnicalReportData.Status result = com.pdsl.reports.proto.TechnicalReportData.Status.valueOf(status_);
    return result == null ? com.pdsl.reports.proto.TechnicalReportData.Status.UNRECOGNIZED : result;
  }

  public static final int FAILING_PHRASE_FIELD_NUMBER = 3;
  private volatile java.lang.Object failingPhrase_;
  /**
   * <code>string failing_phrase = 3;</code>
   */
  public java.lang.String getFailingPhrase() {
    java.lang.Object ref = failingPhrase_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      failingPhrase_ = s;
      return s;
    }
  }
  /**
   * <code>string failing_phrase = 3;</code>
   */
  public com.google.protobuf.ByteString
      getFailingPhraseBytes() {
    java.lang.Object ref = failingPhrase_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      failingPhrase_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FAILURE_REASON_FIELD_NUMBER = 4;
  private volatile java.lang.Object failureReason_;
  /**
   * <code>string failure_reason = 4;</code>
   */
  public java.lang.String getFailureReason() {
    java.lang.Object ref = failureReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      failureReason_ = s;
      return s;
    }
  }
  /**
   * <code>string failure_reason = 4;</code>
   */
  public com.google.protobuf.ByteString
      getFailureReasonBytes() {
    java.lang.Object ref = failureReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      failureReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FAILING_PHRASE_INDEX_FIELD_NUMBER = 5;
  private int failingPhraseIndex_;
  /**
   * <code>uint32 failing_phrase_index = 5;</code>
   */
  public int getFailingPhraseIndex() {
    return failingPhraseIndex_;
  }

  public static final int FILTERED_PHRASE_BODY_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList filteredPhraseBody_;
  /**
   * <code>repeated string filtered_phrase_body = 6;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getFilteredPhraseBodyList() {
    return filteredPhraseBody_;
  }
  /**
   * <code>repeated string filtered_phrase_body = 6;</code>
   */
  public int getFilteredPhraseBodyCount() {
    return filteredPhraseBody_.size();
  }
  /**
   * <code>repeated string filtered_phrase_body = 6;</code>
   */
  public java.lang.String getFilteredPhraseBody(int index) {
    return filteredPhraseBody_.get(index);
  }
  /**
   * <code>repeated string filtered_phrase_body = 6;</code>
   */
  public com.google.protobuf.ByteString
      getFilteredPhraseBodyBytes(int index) {
    return filteredPhraseBody_.getByteString(index);
  }

  public static final int PHRASES_SKIPPED_DUE_TO_FAILURE_FIELD_NUMBER = 7;
  private int phrasesSkippedDueToFailure_;
  /**
   * <code>uint32 phrases_skipped_due_to_failure = 7;</code>
   */
  public int getPhrasesSkippedDueToFailure() {
    return phrasesSkippedDueToFailure_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTestCaseTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, testCaseTitle_);
    }
    if (status_ != com.pdsl.reports.proto.TechnicalReportData.Status.STATUS_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, status_);
    }
    if (!getFailingPhraseBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, failingPhrase_);
    }
    if (!getFailureReasonBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, failureReason_);
    }
    if (failingPhraseIndex_ != 0) {
      output.writeUInt32(5, failingPhraseIndex_);
    }
    for (int i = 0; i < filteredPhraseBody_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, filteredPhraseBody_.getRaw(i));
    }
    if (phrasesSkippedDueToFailure_ != 0) {
      output.writeUInt32(7, phrasesSkippedDueToFailure_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTestCaseTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, testCaseTitle_);
    }
    if (status_ != com.pdsl.reports.proto.TechnicalReportData.Status.STATUS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (!getFailingPhraseBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, failingPhrase_);
    }
    if (!getFailureReasonBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, failureReason_);
    }
    if (failingPhraseIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, failingPhraseIndex_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < filteredPhraseBody_.size(); i++) {
        dataSize += computeStringSizeNoTag(filteredPhraseBody_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFilteredPhraseBodyList().size();
    }
    if (phrasesSkippedDueToFailure_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, phrasesSkippedDueToFailure_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pdsl.reports.proto.TechnicalReportData)) {
      return super.equals(obj);
    }
    com.pdsl.reports.proto.TechnicalReportData other = (com.pdsl.reports.proto.TechnicalReportData) obj;

    boolean result = true;
    result = result && getTestCaseTitle()
        .equals(other.getTestCaseTitle());
    result = result && status_ == other.status_;
    result = result && getFailingPhrase()
        .equals(other.getFailingPhrase());
    result = result && getFailureReason()
        .equals(other.getFailureReason());
    result = result && (getFailingPhraseIndex()
        == other.getFailingPhraseIndex());
    result = result && getFilteredPhraseBodyList()
        .equals(other.getFilteredPhraseBodyList());
    result = result && (getPhrasesSkippedDueToFailure()
        == other.getPhrasesSkippedDueToFailure());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEST_CASE_TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTestCaseTitle().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + FAILING_PHRASE_FIELD_NUMBER;
    hash = (53 * hash) + getFailingPhrase().hashCode();
    hash = (37 * hash) + FAILURE_REASON_FIELD_NUMBER;
    hash = (53 * hash) + getFailureReason().hashCode();
    hash = (37 * hash) + FAILING_PHRASE_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getFailingPhraseIndex();
    if (getFilteredPhraseBodyCount() > 0) {
      hash = (37 * hash) + FILTERED_PHRASE_BODY_FIELD_NUMBER;
      hash = (53 * hash) + getFilteredPhraseBodyList().hashCode();
    }
    hash = (37 * hash) + PHRASES_SKIPPED_DUE_TO_FAILURE_FIELD_NUMBER;
    hash = (53 * hash) + getPhrasesSkippedDueToFailure();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pdsl.reports.proto.TechnicalReportData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdsl.reports.proto.TechnicalReportData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdsl.reports.proto.TechnicalReportData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdsl.reports.proto.TechnicalReportData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdsl.reports.proto.TechnicalReportData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdsl.reports.proto.TechnicalReportData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdsl.reports.proto.TechnicalReportData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pdsl.reports.proto.TechnicalReportData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pdsl.reports.proto.TechnicalReportData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pdsl.reports.proto.TechnicalReportData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pdsl.reports.proto.TechnicalReportData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pdsl.reports.proto.TechnicalReportData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pdsl.reports.proto.TechnicalReportData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.pdsl.reports.proto.TechnicalReportData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.pdsl.reports.proto.TechnicalReportData)
      com.pdsl.reports.proto.TechnicalReportDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pdsl.reports.proto.StrategicReportDataOuterClass.internal_static_com_pdsl_reports_proto_TechnicalReportData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pdsl.reports.proto.StrategicReportDataOuterClass.internal_static_com_pdsl_reports_proto_TechnicalReportData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pdsl.reports.proto.TechnicalReportData.class, com.pdsl.reports.proto.TechnicalReportData.Builder.class);
    }

    // Construct using com.pdsl.reports.proto.TechnicalReportData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      testCaseTitle_ = "";

      status_ = 0;

      failingPhrase_ = "";

      failureReason_ = "";

      failingPhraseIndex_ = 0;

      filteredPhraseBody_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000020);
      phrasesSkippedDueToFailure_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pdsl.reports.proto.StrategicReportDataOuterClass.internal_static_com_pdsl_reports_proto_TechnicalReportData_descriptor;
    }

    @java.lang.Override
    public com.pdsl.reports.proto.TechnicalReportData getDefaultInstanceForType() {
      return com.pdsl.reports.proto.TechnicalReportData.getDefaultInstance();
    }

    @java.lang.Override
    public com.pdsl.reports.proto.TechnicalReportData build() {
      com.pdsl.reports.proto.TechnicalReportData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pdsl.reports.proto.TechnicalReportData buildPartial() {
      com.pdsl.reports.proto.TechnicalReportData result = new com.pdsl.reports.proto.TechnicalReportData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.testCaseTitle_ = testCaseTitle_;
      result.status_ = status_;
      result.failingPhrase_ = failingPhrase_;
      result.failureReason_ = failureReason_;
      result.failingPhraseIndex_ = failingPhraseIndex_;
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        filteredPhraseBody_ = filteredPhraseBody_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000020);
      }
      result.filteredPhraseBody_ = filteredPhraseBody_;
      result.phrasesSkippedDueToFailure_ = phrasesSkippedDueToFailure_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pdsl.reports.proto.TechnicalReportData) {
        return mergeFrom((com.pdsl.reports.proto.TechnicalReportData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pdsl.reports.proto.TechnicalReportData other) {
      if (other == com.pdsl.reports.proto.TechnicalReportData.getDefaultInstance()) return this;
      if (!other.getTestCaseTitle().isEmpty()) {
        testCaseTitle_ = other.testCaseTitle_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getFailingPhrase().isEmpty()) {
        failingPhrase_ = other.failingPhrase_;
        onChanged();
      }
      if (!other.getFailureReason().isEmpty()) {
        failureReason_ = other.failureReason_;
        onChanged();
      }
      if (other.getFailingPhraseIndex() != 0) {
        setFailingPhraseIndex(other.getFailingPhraseIndex());
      }
      if (!other.filteredPhraseBody_.isEmpty()) {
        if (filteredPhraseBody_.isEmpty()) {
          filteredPhraseBody_ = other.filteredPhraseBody_;
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          ensureFilteredPhraseBodyIsMutable();
          filteredPhraseBody_.addAll(other.filteredPhraseBody_);
        }
        onChanged();
      }
      if (other.getPhrasesSkippedDueToFailure() != 0) {
        setPhrasesSkippedDueToFailure(other.getPhrasesSkippedDueToFailure());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pdsl.reports.proto.TechnicalReportData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pdsl.reports.proto.TechnicalReportData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object testCaseTitle_ = "";
    /**
     * <code>string test_case_title = 1;</code>
     */
    public java.lang.String getTestCaseTitle() {
      java.lang.Object ref = testCaseTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testCaseTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_case_title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTestCaseTitleBytes() {
      java.lang.Object ref = testCaseTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testCaseTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_case_title = 1;</code>
     */
    public Builder setTestCaseTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testCaseTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_case_title = 1;</code>
     */
    public Builder clearTestCaseTitle() {
      
      testCaseTitle_ = getDefaultInstance().getTestCaseTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string test_case_title = 1;</code>
     */
    public Builder setTestCaseTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testCaseTitle_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.com.pdsl.reports.proto.TechnicalReportData.Status status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.pdsl.reports.proto.TechnicalReportData.Status status = 2;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.pdsl.reports.proto.TechnicalReportData.Status status = 2;</code>
     */
    public com.pdsl.reports.proto.TechnicalReportData.Status getStatus() {
      @SuppressWarnings("deprecation")
      com.pdsl.reports.proto.TechnicalReportData.Status result = com.pdsl.reports.proto.TechnicalReportData.Status.valueOf(status_);
      return result == null ? com.pdsl.reports.proto.TechnicalReportData.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.pdsl.reports.proto.TechnicalReportData.Status status = 2;</code>
     */
    public Builder setStatus(com.pdsl.reports.proto.TechnicalReportData.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.pdsl.reports.proto.TechnicalReportData.Status status = 2;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object failingPhrase_ = "";
    /**
     * <code>string failing_phrase = 3;</code>
     */
    public java.lang.String getFailingPhrase() {
      java.lang.Object ref = failingPhrase_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        failingPhrase_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string failing_phrase = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFailingPhraseBytes() {
      java.lang.Object ref = failingPhrase_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        failingPhrase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string failing_phrase = 3;</code>
     */
    public Builder setFailingPhrase(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      failingPhrase_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string failing_phrase = 3;</code>
     */
    public Builder clearFailingPhrase() {
      
      failingPhrase_ = getDefaultInstance().getFailingPhrase();
      onChanged();
      return this;
    }
    /**
     * <code>string failing_phrase = 3;</code>
     */
    public Builder setFailingPhraseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      failingPhrase_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object failureReason_ = "";
    /**
     * <code>string failure_reason = 4;</code>
     */
    public java.lang.String getFailureReason() {
      java.lang.Object ref = failureReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        failureReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string failure_reason = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFailureReasonBytes() {
      java.lang.Object ref = failureReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        failureReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string failure_reason = 4;</code>
     */
    public Builder setFailureReason(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      failureReason_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string failure_reason = 4;</code>
     */
    public Builder clearFailureReason() {
      
      failureReason_ = getDefaultInstance().getFailureReason();
      onChanged();
      return this;
    }
    /**
     * <code>string failure_reason = 4;</code>
     */
    public Builder setFailureReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      failureReason_ = value;
      onChanged();
      return this;
    }

    private int failingPhraseIndex_ ;
    /**
     * <code>uint32 failing_phrase_index = 5;</code>
     */
    public int getFailingPhraseIndex() {
      return failingPhraseIndex_;
    }
    /**
     * <code>uint32 failing_phrase_index = 5;</code>
     */
    public Builder setFailingPhraseIndex(int value) {
      
      failingPhraseIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 failing_phrase_index = 5;</code>
     */
    public Builder clearFailingPhraseIndex() {
      
      failingPhraseIndex_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList filteredPhraseBody_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFilteredPhraseBodyIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        filteredPhraseBody_ = new com.google.protobuf.LazyStringArrayList(filteredPhraseBody_);
        bitField0_ |= 0x00000020;
       }
    }
    /**
     * <code>repeated string filtered_phrase_body = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFilteredPhraseBodyList() {
      return filteredPhraseBody_.getUnmodifiableView();
    }
    /**
     * <code>repeated string filtered_phrase_body = 6;</code>
     */
    public int getFilteredPhraseBodyCount() {
      return filteredPhraseBody_.size();
    }
    /**
     * <code>repeated string filtered_phrase_body = 6;</code>
     */
    public java.lang.String getFilteredPhraseBody(int index) {
      return filteredPhraseBody_.get(index);
    }
    /**
     * <code>repeated string filtered_phrase_body = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFilteredPhraseBodyBytes(int index) {
      return filteredPhraseBody_.getByteString(index);
    }
    /**
     * <code>repeated string filtered_phrase_body = 6;</code>
     */
    public Builder setFilteredPhraseBody(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFilteredPhraseBodyIsMutable();
      filteredPhraseBody_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string filtered_phrase_body = 6;</code>
     */
    public Builder addFilteredPhraseBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFilteredPhraseBodyIsMutable();
      filteredPhraseBody_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string filtered_phrase_body = 6;</code>
     */
    public Builder addAllFilteredPhraseBody(
        java.lang.Iterable<java.lang.String> values) {
      ensureFilteredPhraseBodyIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, filteredPhraseBody_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string filtered_phrase_body = 6;</code>
     */
    public Builder clearFilteredPhraseBody() {
      filteredPhraseBody_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string filtered_phrase_body = 6;</code>
     */
    public Builder addFilteredPhraseBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFilteredPhraseBodyIsMutable();
      filteredPhraseBody_.add(value);
      onChanged();
      return this;
    }

    private int phrasesSkippedDueToFailure_ ;
    /**
     * <code>uint32 phrases_skipped_due_to_failure = 7;</code>
     */
    public int getPhrasesSkippedDueToFailure() {
      return phrasesSkippedDueToFailure_;
    }
    /**
     * <code>uint32 phrases_skipped_due_to_failure = 7;</code>
     */
    public Builder setPhrasesSkippedDueToFailure(int value) {
      
      phrasesSkippedDueToFailure_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 phrases_skipped_due_to_failure = 7;</code>
     */
    public Builder clearPhrasesSkippedDueToFailure() {
      
      phrasesSkippedDueToFailure_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.pdsl.reports.proto.TechnicalReportData)
  }

  // @@protoc_insertion_point(class_scope:com.pdsl.reports.proto.TechnicalReportData)
  private static final com.pdsl.reports.proto.TechnicalReportData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pdsl.reports.proto.TechnicalReportData();
  }

  public static com.pdsl.reports.proto.TechnicalReportData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TechnicalReportData>
      PARSER = new com.google.protobuf.AbstractParser<TechnicalReportData>() {
    @java.lang.Override
    public TechnicalReportData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TechnicalReportData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TechnicalReportData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TechnicalReportData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pdsl.reports.proto.TechnicalReportData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

