// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/pdsl/reports/proto/StrategicReportData.proto

package com.pdsl.reports.proto;

public interface TestCaseGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.pdsl.reports.proto.TestCaseGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
   */
  java.util.List<com.pdsl.reports.proto.TechnicalReportData> 
      getTechnicalReportDataList();
  /**
   * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
   */
  com.pdsl.reports.proto.TechnicalReportData getTechnicalReportData(int index);
  /**
   * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
   */
  int getTechnicalReportDataCount();
  /**
   * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
   */
  java.util.List<? extends com.pdsl.reports.proto.TechnicalReportDataOrBuilder> 
      getTechnicalReportDataOrBuilderList();
  /**
   * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
   */
  com.pdsl.reports.proto.TechnicalReportDataOrBuilder getTechnicalReportDataOrBuilder(
      int index);
}
