// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/pdsl/reports/proto/StrategicReportData.proto

package com.pdsl.reports.proto;

/**
 * Protobuf type {@code com.pdsl.reports.proto.TestCaseGroup}
 */
public  final class TestCaseGroup extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.pdsl.reports.proto.TestCaseGroup)
    TestCaseGroupOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TestCaseGroup.newBuilder() to construct.
  private TestCaseGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TestCaseGroup() {
    technicalReportData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TestCaseGroup(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              technicalReportData_ = new java.util.ArrayList<com.pdsl.reports.proto.TechnicalReportData>();
              mutable_bitField0_ |= 0x00000001;
            }
            technicalReportData_.add(
                input.readMessage(com.pdsl.reports.proto.TechnicalReportData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        technicalReportData_ = java.util.Collections.unmodifiableList(technicalReportData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pdsl.reports.proto.StrategicReportDataOuterClass.internal_static_com_pdsl_reports_proto_TestCaseGroup_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pdsl.reports.proto.StrategicReportDataOuterClass.internal_static_com_pdsl_reports_proto_TestCaseGroup_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pdsl.reports.proto.TestCaseGroup.class, com.pdsl.reports.proto.TestCaseGroup.Builder.class);
  }

  public static final int TECHNICAL_REPORT_DATA_FIELD_NUMBER = 1;
  private java.util.List<com.pdsl.reports.proto.TechnicalReportData> technicalReportData_;
  /**
   * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
   */
  public java.util.List<com.pdsl.reports.proto.TechnicalReportData> getTechnicalReportDataList() {
    return technicalReportData_;
  }
  /**
   * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
   */
  public java.util.List<? extends com.pdsl.reports.proto.TechnicalReportDataOrBuilder> 
      getTechnicalReportDataOrBuilderList() {
    return technicalReportData_;
  }
  /**
   * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
   */
  public int getTechnicalReportDataCount() {
    return technicalReportData_.size();
  }
  /**
   * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
   */
  public com.pdsl.reports.proto.TechnicalReportData getTechnicalReportData(int index) {
    return technicalReportData_.get(index);
  }
  /**
   * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
   */
  public com.pdsl.reports.proto.TechnicalReportDataOrBuilder getTechnicalReportDataOrBuilder(
      int index) {
    return technicalReportData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < technicalReportData_.size(); i++) {
      output.writeMessage(1, technicalReportData_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < technicalReportData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, technicalReportData_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pdsl.reports.proto.TestCaseGroup)) {
      return super.equals(obj);
    }
    com.pdsl.reports.proto.TestCaseGroup other = (com.pdsl.reports.proto.TestCaseGroup) obj;

    boolean result = true;
    result = result && getTechnicalReportDataList()
        .equals(other.getTechnicalReportDataList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTechnicalReportDataCount() > 0) {
      hash = (37 * hash) + TECHNICAL_REPORT_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getTechnicalReportDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pdsl.reports.proto.TestCaseGroup parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdsl.reports.proto.TestCaseGroup parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdsl.reports.proto.TestCaseGroup parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdsl.reports.proto.TestCaseGroup parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdsl.reports.proto.TestCaseGroup parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdsl.reports.proto.TestCaseGroup parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdsl.reports.proto.TestCaseGroup parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pdsl.reports.proto.TestCaseGroup parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pdsl.reports.proto.TestCaseGroup parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pdsl.reports.proto.TestCaseGroup parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pdsl.reports.proto.TestCaseGroup parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pdsl.reports.proto.TestCaseGroup parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pdsl.reports.proto.TestCaseGroup prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.pdsl.reports.proto.TestCaseGroup}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.pdsl.reports.proto.TestCaseGroup)
      com.pdsl.reports.proto.TestCaseGroupOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pdsl.reports.proto.StrategicReportDataOuterClass.internal_static_com_pdsl_reports_proto_TestCaseGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pdsl.reports.proto.StrategicReportDataOuterClass.internal_static_com_pdsl_reports_proto_TestCaseGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pdsl.reports.proto.TestCaseGroup.class, com.pdsl.reports.proto.TestCaseGroup.Builder.class);
    }

    // Construct using com.pdsl.reports.proto.TestCaseGroup.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTechnicalReportDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (technicalReportDataBuilder_ == null) {
        technicalReportData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        technicalReportDataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pdsl.reports.proto.StrategicReportDataOuterClass.internal_static_com_pdsl_reports_proto_TestCaseGroup_descriptor;
    }

    @java.lang.Override
    public com.pdsl.reports.proto.TestCaseGroup getDefaultInstanceForType() {
      return com.pdsl.reports.proto.TestCaseGroup.getDefaultInstance();
    }

    @java.lang.Override
    public com.pdsl.reports.proto.TestCaseGroup build() {
      com.pdsl.reports.proto.TestCaseGroup result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pdsl.reports.proto.TestCaseGroup buildPartial() {
      com.pdsl.reports.proto.TestCaseGroup result = new com.pdsl.reports.proto.TestCaseGroup(this);
      int from_bitField0_ = bitField0_;
      if (technicalReportDataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          technicalReportData_ = java.util.Collections.unmodifiableList(technicalReportData_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.technicalReportData_ = technicalReportData_;
      } else {
        result.technicalReportData_ = technicalReportDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pdsl.reports.proto.TestCaseGroup) {
        return mergeFrom((com.pdsl.reports.proto.TestCaseGroup)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pdsl.reports.proto.TestCaseGroup other) {
      if (other == com.pdsl.reports.proto.TestCaseGroup.getDefaultInstance()) return this;
      if (technicalReportDataBuilder_ == null) {
        if (!other.technicalReportData_.isEmpty()) {
          if (technicalReportData_.isEmpty()) {
            technicalReportData_ = other.technicalReportData_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTechnicalReportDataIsMutable();
            technicalReportData_.addAll(other.technicalReportData_);
          }
          onChanged();
        }
      } else {
        if (!other.technicalReportData_.isEmpty()) {
          if (technicalReportDataBuilder_.isEmpty()) {
            technicalReportDataBuilder_.dispose();
            technicalReportDataBuilder_ = null;
            technicalReportData_ = other.technicalReportData_;
            bitField0_ = (bitField0_ & ~0x00000001);
            technicalReportDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTechnicalReportDataFieldBuilder() : null;
          } else {
            technicalReportDataBuilder_.addAllMessages(other.technicalReportData_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pdsl.reports.proto.TestCaseGroup parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pdsl.reports.proto.TestCaseGroup) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.pdsl.reports.proto.TechnicalReportData> technicalReportData_ =
      java.util.Collections.emptyList();
    private void ensureTechnicalReportDataIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        technicalReportData_ = new java.util.ArrayList<com.pdsl.reports.proto.TechnicalReportData>(technicalReportData_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.pdsl.reports.proto.TechnicalReportData, com.pdsl.reports.proto.TechnicalReportData.Builder, com.pdsl.reports.proto.TechnicalReportDataOrBuilder> technicalReportDataBuilder_;

    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public java.util.List<com.pdsl.reports.proto.TechnicalReportData> getTechnicalReportDataList() {
      if (technicalReportDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(technicalReportData_);
      } else {
        return technicalReportDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public int getTechnicalReportDataCount() {
      if (technicalReportDataBuilder_ == null) {
        return technicalReportData_.size();
      } else {
        return technicalReportDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public com.pdsl.reports.proto.TechnicalReportData getTechnicalReportData(int index) {
      if (technicalReportDataBuilder_ == null) {
        return technicalReportData_.get(index);
      } else {
        return technicalReportDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public Builder setTechnicalReportData(
        int index, com.pdsl.reports.proto.TechnicalReportData value) {
      if (technicalReportDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTechnicalReportDataIsMutable();
        technicalReportData_.set(index, value);
        onChanged();
      } else {
        technicalReportDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public Builder setTechnicalReportData(
        int index, com.pdsl.reports.proto.TechnicalReportData.Builder builderForValue) {
      if (technicalReportDataBuilder_ == null) {
        ensureTechnicalReportDataIsMutable();
        technicalReportData_.set(index, builderForValue.build());
        onChanged();
      } else {
        technicalReportDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public Builder addTechnicalReportData(com.pdsl.reports.proto.TechnicalReportData value) {
      if (technicalReportDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTechnicalReportDataIsMutable();
        technicalReportData_.add(value);
        onChanged();
      } else {
        technicalReportDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public Builder addTechnicalReportData(
        int index, com.pdsl.reports.proto.TechnicalReportData value) {
      if (technicalReportDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTechnicalReportDataIsMutable();
        technicalReportData_.add(index, value);
        onChanged();
      } else {
        technicalReportDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public Builder addTechnicalReportData(
        com.pdsl.reports.proto.TechnicalReportData.Builder builderForValue) {
      if (technicalReportDataBuilder_ == null) {
        ensureTechnicalReportDataIsMutable();
        technicalReportData_.add(builderForValue.build());
        onChanged();
      } else {
        technicalReportDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public Builder addTechnicalReportData(
        int index, com.pdsl.reports.proto.TechnicalReportData.Builder builderForValue) {
      if (technicalReportDataBuilder_ == null) {
        ensureTechnicalReportDataIsMutable();
        technicalReportData_.add(index, builderForValue.build());
        onChanged();
      } else {
        technicalReportDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public Builder addAllTechnicalReportData(
        java.lang.Iterable<? extends com.pdsl.reports.proto.TechnicalReportData> values) {
      if (technicalReportDataBuilder_ == null) {
        ensureTechnicalReportDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, technicalReportData_);
        onChanged();
      } else {
        technicalReportDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public Builder clearTechnicalReportData() {
      if (technicalReportDataBuilder_ == null) {
        technicalReportData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        technicalReportDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public Builder removeTechnicalReportData(int index) {
      if (technicalReportDataBuilder_ == null) {
        ensureTechnicalReportDataIsMutable();
        technicalReportData_.remove(index);
        onChanged();
      } else {
        technicalReportDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public com.pdsl.reports.proto.TechnicalReportData.Builder getTechnicalReportDataBuilder(
        int index) {
      return getTechnicalReportDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public com.pdsl.reports.proto.TechnicalReportDataOrBuilder getTechnicalReportDataOrBuilder(
        int index) {
      if (technicalReportDataBuilder_ == null) {
        return technicalReportData_.get(index);  } else {
        return technicalReportDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public java.util.List<? extends com.pdsl.reports.proto.TechnicalReportDataOrBuilder> 
         getTechnicalReportDataOrBuilderList() {
      if (technicalReportDataBuilder_ != null) {
        return technicalReportDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(technicalReportData_);
      }
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public com.pdsl.reports.proto.TechnicalReportData.Builder addTechnicalReportDataBuilder() {
      return getTechnicalReportDataFieldBuilder().addBuilder(
          com.pdsl.reports.proto.TechnicalReportData.getDefaultInstance());
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public com.pdsl.reports.proto.TechnicalReportData.Builder addTechnicalReportDataBuilder(
        int index) {
      return getTechnicalReportDataFieldBuilder().addBuilder(
          index, com.pdsl.reports.proto.TechnicalReportData.getDefaultInstance());
    }
    /**
     * <code>repeated .com.pdsl.reports.proto.TechnicalReportData technical_report_data = 1;</code>
     */
    public java.util.List<com.pdsl.reports.proto.TechnicalReportData.Builder> 
         getTechnicalReportDataBuilderList() {
      return getTechnicalReportDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.pdsl.reports.proto.TechnicalReportData, com.pdsl.reports.proto.TechnicalReportData.Builder, com.pdsl.reports.proto.TechnicalReportDataOrBuilder> 
        getTechnicalReportDataFieldBuilder() {
      if (technicalReportDataBuilder_ == null) {
        technicalReportDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.pdsl.reports.proto.TechnicalReportData, com.pdsl.reports.proto.TechnicalReportData.Builder, com.pdsl.reports.proto.TechnicalReportDataOrBuilder>(
                technicalReportData_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        technicalReportData_ = null;
      }
      return technicalReportDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.pdsl.reports.proto.TestCaseGroup)
  }

  // @@protoc_insertion_point(class_scope:com.pdsl.reports.proto.TestCaseGroup)
  private static final com.pdsl.reports.proto.TestCaseGroup DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pdsl.reports.proto.TestCaseGroup();
  }

  public static com.pdsl.reports.proto.TestCaseGroup getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TestCaseGroup>
      PARSER = new com.google.protobuf.AbstractParser<TestCaseGroup>() {
    @java.lang.Override
    public TestCaseGroup parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TestCaseGroup(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TestCaseGroup> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TestCaseGroup> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pdsl.reports.proto.TestCaseGroup getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

