= Troubleshooting ANTLR4 error messages

== Things to always do:

=== Always provide an implementation for visitErrorNode

Sometimes when people creating languages see a problem in the user's input, they may want
to react to it in some way. This might be to provide a more helpful error message or try
to recover the program in some way. *By default, _visitErrorNode_ does nothing*!

This is probably not what you want to do.

This can cause difficult to debug problems because ANTLR4 automatically tries it's best to
recover and acts like nothing went wrong. When it crashes in these circumstances it isn't
clear to you that the application crashed because of some problem with the grammar you
wrote.

Always provide an implementation, preferably that throws a runtime exception:

```
public MyCustomVisitor implements MyCustomParserVisitor<Void> {

    public Void visitErrorNode(ErrorNode node) {
        throw new IllegalStateException("There was an error in the grammar! Check the G4 files for the issue!");
    }
}
```

=== Use Lexer modes to parse generic parameters

Ambiguity is the bane of a parser.

See <<tutorials/parameters.adoc#island-grammars, Parameters>> for more detail on how to use lexer modes or "island grammars" to solve this problem.

=== Separate your DEFAULT lexemes from the lexer mode lexemes [[separate-parameters]]

Always place lexer modes at the bottom of your file. If you place a lexer mode in the
middle of your file *it will treat everything beneath it as part of that lexer mode!*

```
lexer grammar modeMistakeLexer;

  FOO: 'foo' -> mode(BAR_MODE);

mode BAR_MODE;
    BAR: -> 'bar ' -> mode(DEFAULT_MODE);

BIZZ: 'bizz'; // <-- This is part of BAR_MODE!

mode BAZZ_MODE;
    BAZZ: -> 'bazz ' -> mode(DEFAULT_MODE);

```

This can create difficult to debug errors because in your head you assume that tokens like
`BIZZ` are visible in the current parser context. The reality is probably that you can no longer even _see_ that token because it only exists in a different mode you've since exited.

In this situation ANLTR will spit a lot of _token recognition errors_ out leaving you wondering why it can't see the thing clearly written in your lexer.
Indentation is ignored by ANTLR, but it may cause _you_ to think it exists in a different context.

The solution is to remember to group modes together at the bottom of the file:

```
lexer grammar modeMistakeLexer;

FOO: 'foo' -> mode(BAR_MODE);
BIZZ: 'bizz'; // <-- This is part of BAR_MODE!

mode BAR_MODE;
    BAR: -> 'bar ' -> mode(DEFAULT_MODE);

mode BAZZ_MODE;
    BAZZ: -> 'bazz ' -> mode(DEFAULT_MODE);
```

=== Don't create duplicate start or recognizer rules in imported parsers

In fact, don't have rules with duplicate names shared across your grammars in general.

PDSL by default expects you to provide a `polymorphicDslAllRules` and `polymorphicDslSyntaxCheck` unless you explicitly provide different rules.

These are necessary so the framework knows whether your DSL test is written correctly and so it can execute on specific sentences:

```
parser grammar MyMainParser;

options {tokenVocab=MyMainLexer; }

myFirstRule: MY_FIRST_RULE;
mySecondRule: MY_SECOND_RULE;

// The rules must go in this specific order and can repeat as many times as needed
polymorphicDslSyntaxCheck: (myFirstRule mySecondRule)+;

// either rule can be executed on as a sentence
polymorphicDslAllRules: (
	myFirstRule
	| mySecondRule
)+;
```

However having your recognizer rule and start rule in the same file can cause a problem if you import another parser:


```
parser grammar OtherParser;

options {tokenVocab=OtherLexer; }

myThirdRule: MY_THIRD_RULE;
myFourthRule: MY_FOURTH_RULE;


polymorphicDslSyntaxCheck: (myThirdRule myFourthRule)+;
polymorphicDslAllRules: (myThirdRule | myFourthRule)+;
```

```
parser grammar MyMainParser;

import OtherParser; // OH NO! This parser has conflicting rule names for the recognizer and start rule!

options {tokenVocab=MyMainLexer; }

myFirstRule: MY_FIRST_RULE;
mySecondRule: MY_SECOND_RULE;

// The rules must go in this specific order and can repeat as many times as needed
polymorphicDslSyntaxCheck: ((myFirstRule mySecondRule) | (myThirdRule myFourthRule))+;

// either rule can be executed on as a sentence
polymorphicDslAllRules: (
	myFirstRule
	| mySecondRule
	| myThirdRule
	| myFourthRule
)+;

```

ANTLR will fail is subtle ways when rule names collide. The solution here is to have your recognizer and start rule defined in their own file and never have these in shared parser .g4 files:


```
parser grammar OtherParser;

options {tokenVocab=OtherLexer; }

myThirdRule: MY_THIRD_RULE;
myFourthRule: MY_FOURTH_RULE;


// Removed start rule and syntax check
```

```
parser grammar MyMainParser;

import OtherParser; // OH NO! This parser has conflicting rule names for the recognizer and start rule!

options {tokenVocab=MyMainLexer; }

myFirstRule: MY_FIRST_RULE;
mySecondRule: MY_SECOND_RULE;

// Removed start rule and syntax check
```

```
parser grammar PdslMyMainParser;

options {tokenVocab=MyMainLexer; }


// The syntax rule here doesn't conflict with any imported parser
polymorphicDslSyntaxCheck: ((myFirstRule mySecondRule) | (myThirdRule myFourthRule))+;

// The start rule here doesn't conflict with any imported parser
polymorphicDslAllRules: (
	myFirstRule
	| mySecondRule
	| myThirdRule
	| myFourthRule
)+;
```
